# This is a basic workflow to help you get started with Actions

name: Pull Request Checker

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  lint:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        
      - name: Setup Python
        uses: actions/setup-python@v2.1.4
  
      - name: Install yamllint
        run: pip install --user yamllint
          
      - name: Lint yaml
        run: yamllint *.yml
          
      - name: Check typos
        run: |
          mkdir -p ~/.bin
          curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh | sh -s -- -b ~/.bin v0.10.0
          curl -sfL https://git.io/misspell | sh -s -- -b ~/.bin
          find *.md -print0 | xargs -0 ~/.bin/misspell | ~/.bin/reviewdog -efm="%f:%l:%c: %m" -name="misspell" -reporter=github-pr-check -level=error
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
